name: SenPayment Auto Preorder
on:
  workflow_dispatch: # Mengizinkan trigger dari luar (API/Cron external)

jobs:
  run-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Menggunakan versi Node terbaru yang mendukung native fetch

      - name: Install Dependencies
        run: npm install

      - name: Jalankan Worker SenPayment
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          KHFY_KEY: ${{ secrets.KHFY_KEY }}
          ICS_KEY: ${{ secrets.ICS_KEY }}
        run: npm start
